shell = "bash -c '{}'"
default-theme = "base16-tomorrow-night"
# hooks = ["mkdir -p ~/.config/nvim && ln -sf ${HOME}/.local/share/tinted-theming/tinty/repos/tinted-vim/colors ${HOME}/.config/nvim/colors"]

[[items]]
path = "https://github.com/tinted-theming/tinted-terminal"
name = "tinted-terminal-kitty"
themes-dir = "themes/kitty"
hook = "kitten @ load-config >/dev/null 2>&1 || true"
supported-systems = ["base16", "base24"]

#[[items]]
#path = "https://github.com/tinted-theming/tinted-terminal"
#name = "tinted-terminal-iterm2"
## themes-dir = "themes/iterm2"
#themes-dir = "themes-16/iterm2-applescripts"
#hook = '''
#command cp -f %f ~/Library/Application\ Support/iTerm2/Scripts/AutoLaunch.scpt \
#  && osascript %f >/dev/null 2>&1 || true
#'''
#supported-systems = ["base16", "base24"]

[[items]]
path = "https://github.com/tinted-theming/tinted-terminal"
name = "tinted-terminal-wezterm"
themes-dir = "themes/wezterm"
hook = '''
ln -sf "${HOME}/.local/share/tinted-theming/tinty/repos/tinted-terminal-wezterm/themes/wezterm" "${HOME}/.config/wezterm/colors" \
  && wezterm cli set-color-scheme %f >/dev/null 2>&1 || true
'''
# hook = '''
# cp %f ~/.config/wezterm/colors/%~nxf >/dev/null 2>&1 || true \
#   && wezterm cli set-color-scheme %f >/dev/null 2>&1 || true
# '''
supported-systems = ["base16", "base24"]

[[items]]
path = "https://github.com/tinted-theming/tinted-shell"
name = "tinted-shell"
themes-dir = "scripts"
hook = "source \"$TINTY_THEME_FILE_PATH\""
supported-systems = ["base16", "base24"]

[[items]]
path = "https://github.com/tinted-theming/tinted-tmux"
name = "tinted-tmux"
themes-dir = "colors"
hook = "tmux run 2> /dev/null && tmux source-file %f"

[[items]]
path = "https://github.com/tinted-theming/tinted-vim"
name = "tinted-vim"
themes-dir = "colors"
hook = '''
mkdir -p ~/.config/nvim && ln -sf "${HOME}/.local/share/tinted-theming/tinty/repos/tinted-vim/colors" "${HOME}/.config/nvim/colors"
'''

