---
configure_homebrew: true
homebrew_taps:
  - 1password/tap
  - atlassian/homebrew-acli
  - carvel-dev/carvel
  - clojure-lsp/brew
  - git-chglog/git-chglog
  - hashicorp/tap
  - infrahq/tap
  - jmespath/jmespath
  # - johanhaleby/kubetail
  - minamijoyo/hcledit
  - rest-sh/tap
  - shivammathur/php
  - tilt-dev/tap
  - tinted-theming/tinted
  - warrensbox/tap

homebrew_installed_packages:
  - ack
  - atlassian/homebrew-acli/acli
  - autoconf
  - automake
  - awscli
  - bash
  - bash-completion@2
  - borkdude/brew/babashka
  - certstrap
  - cfssl
  - clojure-lsp/brew/clojure-lsp-native
  - clojure/tools/clojure
  - commitizen
  - conftest
  - coreutils
  - cowsay
  - crane
  - ctags
  - curl
  - diffutils
  - direnv
  - dos2unix
  - duckdb
  - emscripten
  - fd
  - findutils
  - font-hack-nerd-font
  - gawk
  - gettext
  - gh
  - git
  - git-chglog
  - git-delta
  - git-gui
  - git-lfs
  - git-svn
  - gnu-getopt
  - gnu-sed
  - gnu-tar
  - gnutls
  - go
  - go-jira
  - gpg
  - grep
  - grepcidr
  - grpcurl
  - hashicorp/tap/boundary
  - hashicorp/tap/consul
  - hashicorp/tap/hashicorp-boundary-desktop
  - hashicorp/tap/nomad
  - hashicorp/tap/packer
  - hashicorp/tap/terraform-ls
  - hcl2json
  - helm
  - htop
  - iam-policy-json-to-terraform
  - ifstat
  - imagemagick
  - infrahq/tap/infra
  - iperf
  - iperf3
  - jd
  - jfrog-cli
  - jmespath/jmespath/jp
  - jmeter
  - jq
  - keybase
  # - kops
  # - krew
  # - kubebuilder
  # - kubectx
  # - kubernetes-cli
  # - kubetail
  - lazygit
  - libevent
  - linkerd
  - mcrypt
  - minamijoyo/hcledit/hcledit
  # - minikube
  - mtr
  - mupdf-tools
  - ncdu
  - ncurses
  - netcat
  - nmap
  - node
  - nvim
  - nvm
  - openssl
  - pre-commit
  - pv
  - pwgen
  - pyenv
  - raylib
  - readline
  - reattach-to-user-namespace
  - ripgrep
  - rlwrap
  - rsync
  - shellcheck
  - shivammathur/php/php@5.6
  - socat
  - sops
  - sqlite
  - ssh-copy-id
  - stern
  - telnet
  - terraform-docs
  - tflint
  - tfswitch
  - tgswitch
  - tig
  - tilt-dev/tap/ctlptl
  - tilt-dev/tap/tilt
  - tinted-theming/tinted/tinty
  - tmux
  - tree
  - tree-sitter
  - tree-sitter-cli
  - typescript
  - uv
  - vault
  - vim
  - watch
  - wget
  - wrk
  - xz
  - yq
  - ytt

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - bruno
  - docker
  - firefox
  - iterm2
  - maccy
  - rectangle
  - restish
  - session-manager-plugin
  - visual-studio-code

