---
configure_homebrew: true
homebrew_taps:
  - 1password/tap
  - carvel-dev/carvel
  - clojure-lsp/brew
  - git-chglog/git-chglog
  - hashicorp/tap
  - infrahq/tap
  - jmespath/jmespath
  - johanhaleby/kubetail
  - minamijoyo/hcledit
  - rest-sh/tap
  - tilt-dev/tap
  - tinted-theming/tinted
  - warrensbox/tap

homebrew_installed_packages:
  - ack
  - autoconf
  - automake
  - awscli
  - bash
  - bash-completion@2
  - borkdude/brew/babashka
  - certstrap
  - cfssl
  - clojure-lsp/brew/clojure-lsp-native
  - clojure/tools/clojure
  - commitizen
  - conftest
  - coreutils
  - cowsay
  - crane
  - ctags
  - curl
  - diffutils
  - direnv
  - dos2unix
  - duckdb
  - fd
  - findutils
  - font-hack-nerd-font
  - gawk
  - gettext
  - gh
  - git
  - git-chglog
  - git-delta
  - git-gui
  - git-lfs
  - git-svn
  - gnu-getopt
  - gnu-sed
  - gnu-tar
  - gnutls
  - go
  - golang-migrate
  - gpg
  - grep
  - grepcidr
  - grpcurl
  - hashicorp/tap/consul
  - hashicorp/tap/nomad
  - hashicorp/tap/packer
  - hashicorp/tap/terraform-ls
  - hcl2json
  - helm
  - htop
  - iam-policy-json-to-terraform
  - ifstat
  - imagemagick
  - infrahq/tap/infra
  - iperf
  - iperf3
  - jd
  - jmespath/jmespath/jp
  - jmeter
  - jq
  - kops
  - krew
  - kubebuilder
  - kubectx
  - kubernetes-cli
  - kubetail
  - lazygit
  - libevent
  - linkerd
  #- mcrypt
  - minamijoyo/hcledit/hcledit
  - minikube
  - mtr
  - mupdf-tools
  - ncdu
  - ncurses
  - netcat
  - nmap
  - node
  - nvim
  - nvm
  - openssl
  - pre-commit
  - pv
  - pwgen
  - pyenv
  - raylib
  - readline
  - reattach-to-user-namespace
  - ripgrep
  - rlwrap
  - rsync
  - shellcheck
  - socat
  - sops
  - sqlite
  - ssh-copy-id
  - stern
  - telnet
  - terraform-docs
  - tflint
  - tfswitch
  - tgswitch
  - tig
  - tilt-dev/tap/ctlptl
  - tilt-dev/tap/tilt
  - tinted-theming/tinted/tinty
  - tmux
  - tree
  - tree-sitter
  - tree-sitter-cli
  - typescript
  - uv
  - vault
  - vim
  - tfswitch
  - tgswitch
  - watch
  - wget
  - wrk
  - xz
  - yq
  - ytt

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - 1password
  - 1password-cli
  - a-better-finder-attributes
  - a-better-finder-rename
  - affinity
  - apparency
  - archaeology
  - audio-hijack
  - balenaetcher
  - bartender
  - beyond-compare
  - big-mean-folder-machine
  - carbon-copy-cloner
  - charles
  - colorsnapper
  - daisydisk
  - docker
  - downie
  - drivedx
  - dropbox
  - farrago
  - firefox
  - fission
  - gpg-suite-no-mail
  - guitar-pro
  - imageoptim
  - istat-menus
  - jetbrains-toolbox
  - jordanbaird-ice
  - keybase
  - loopback
  - maccy
  - marked-app
  - monodraw
  - obsidian
  - pacifist
  - paragon-extfs
  - paragon-ntfs
  - permute
  - postgres-unofficial
  - reaper
  - rectangle
  - restish
  - ripx
  - screens
  - screens-connect
  - signal
  - snagit
  - soundsource
  - sourcetree
  - spotify
  - suspicious-package
  - syncthing
  - tailscale-app
  - transcribe
  - typora
  - vagrant
  - virtualbox
  - visual-studio-code
  - wacom-tablet
  - wezterm
  - wireshark-app

  #- bruno
  #- cinch
  #- cursorsense
  #- evernote
  #- iterm2
  #- session-manager-plugin # no longer supported
  #- sizeup
  #- steermouse
  #- virtualbox-extension-pack

